### ISSUE TITLE
Apple Pay SDK v1.1.0 doesn't export ApplePaySession

### ISSUE THREAD

**Issue by vikrantuk** [johan44co/apple-pay-button#1]
Hi @johan44co , thank you for the awesome library.

I observed that apple-pay-sdk v1.1.0 which is being used doesn't export the ApplePaySession into window which is essential to complete the payment.
If [https://github.com/johan44co/apple-pay-button/blob/ad498f05daa61bf346957d63204b361c2e4d0bb9/src/index.tsx#L56](url) is changed to:
script.src = 'https://applepay.cdn-apple.com/jsapi/1.latest/apple-pay-sdk.js';
will resolve the issue.

I tried adding latest script tag in my web application but as both scripts are defining custom element under 'apple-pay-button'

**Comment by johan44co** [comment]
I merged your [PR](https://github.com/johan44co/apple-pay-button/pull/2) related to this issue. A new version will be released including this fix.

**Comment by johan44co** [comment]
@vikrantuk a new version with the fix is out:)

**Comment by vikrantuk** [comment]
@johan44co Thank you 👍

**Comment by johan44co** [comment]
You are welcome @vikrantuk the right version with the fix is version 1.1.6
